### PR TITLE
Adjusted EffectComposer PixelRatio

### PR DESCRIPTION
**Pull request by stephencorwin**
following up from https://github.com/react-spring/react-postprocessing/pull/29
> (I thought the fix was applying a pixel ratio to their canvas as well, but that didn't help

If applying the pixel ratio to the canvas in the examples wasn't the issue, we should remove it from them.

Also, it is better to use the pixel ratio coming from `gl.pixelRatio` so that if the `pixelRatio` prop is set on the `<Canvas />`, the correct pixel ratio is inherited.

```jsx
<Canvas pixelRatio={2} />
```
image

You can see where R3F sets this property here:
https://github.com/react-spring/react-three-fiber/blob/master/src/canvas.tsx#L563

### CODE REVIEW

**Comment by stephencorwin** [comment]
@drcmda something we should consider in the future is to use a resize observer to correctly recalculate the devicePixelRatio if the user starts on one monitor and switches to a different one. I'm not sure, but I don't think we account for this yet in R3F.

**Comment by CharlieHess** [comment]
ah, makes sense. thanks for the follow-up @stephencorwin 👍

**Comment by drcmda** [comment]
yes for sure, we should expose canvas pr and rely on it. there is a resize observer on the container that holds the canvas - but pixelratio is still something that's being passed down as an argument by the user. i guess it would have to be a function, so that we can call it on resize changes, that would take care of multi monitor situations (though i still dont think the browser is clever enough to invalidate resize if you merely drag it from this screen to that screen).

**Comment by stephencorwin** [comment]
@drcmda, I just remembered a colleague of mine solved this by observing changes on devicePixelRatio directly rather than the resize event. It can even be abstracted into a hook.
```diff
// in canvas.tsx
+ const pixelRatio = useDevicePixelRatio()
useLayoutEffect(() => void (pixelRatio && gl.setPixelRatio(pixelRatio)), [gl, pixelRatio])
```
I'll see if I can add this to the `v5` changeset.

**Comment by drcmda** [comment]
It depends on how complex it would be, if it adds too much weight I'd prefer a user land solution. Thinking of it, it's probably the users responsibility anyway to set and observe Pixelratio because it can't be set by r3f since it looks performance (some devices have a tattoo of 4 and higher). But we should at least expose it so that libs like rpp can always react to changes to it.

**Pull request merged**
